# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-09-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegAndLoginApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_like', models.CharField(max_length=100)),
                ('user_like', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
            ],
        ),
    ]
